packages/detox/build/withDetoxProjectGradle.d.ts, packages/detox/build/withDetoxProjectGradle.js, packages/detox/build/withProguardGradle.js, packages/detox/src/withDetoxProjectGradle.ts, packages/detox/src/withProguardGradle.ts
Support detox not being in the closest node_modules folder, this appears to be the issue here https://github.com/expo/config-plugins/runs/4359662772?check_suite_focus=true
=> [detox] improved monorepo support

apps/app/.gitignore, apps/app/detox.config.js, apps/app/scripts/build-detox-ios.sh, apps/app/scripts/start-metro.sh
I don't known why, but iOS release build still crashed on start. Look like it related to expo-updates module.
```
Application Specific Information:
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
CoreSimulator 776.4 - Device: iPhone 13 Pro (152AB63A-3F82-4D26-9AE3-36207700E62C) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 13 Pro
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'expo-updates is enabled, but no valid URL is configured under EXUpdatesURL. If you are making a release build for the first time, make sure you have run `expo publish` …
```
=> chore: added start-metro script

packages/react-native-callkeep/src/withCallkeep.ts
The `xcode` module used to update the XCode files is directly setting the `ATTRIBUTES` key for us:
https://github.com/apache/cordova-node-xcode/blob/8b98cabc5978359db88dc9ff2d4c015cba40f150/lib/pbxFile.js#L215-L216
In that case, we simply need to pass `weak: true` instead of the full `settings` object.
=> Fix optional status in withXcodeLinkBinaryWithLibraries

.github/workflows/test.yml, packages/ios-stickers/build/options.json, packages/ios-stickers/build/withStickerPack.js, packages/ios-stickers/jest.config.js, packages/ios-stickers/package.json, packages/ios-stickers/src/__tests__/withStickerPack-test.ts, packages/ios-stickers/src/options.json, packages/ios-stickers/src/withStickerPack.ts, packages/ios-stickers/tsconfig.json, yarn.lock
Experiment with using `schema-utils` from Webpack to validate the TypeScript properties and throw an error during introspection and prebuilding. 
This looks something like:
```
Invalid options object. @config-plugins/ios-stickers has been initialized using an options object that does not match the API schema.
- options.stickers[0] should be one of these:
string | object { image, name?, accessibilityLabel? }
Details:
* options.stickers[0] should be a string.
* options.stickers[0] should be an object:
object { image, name?, accessibilityLabel? }
- options.columns should be one of these:
2 | 3 | 4
ValidationError: Invalid options object. @config-plugins/ios-stickers has been initialized using an options object that does not match the API schema.
- options.stickers[0] should be one of these: …
```
=> [ios-stickers] Added JSON schema validation

packages/react-native-webrtc/build/withBitcodeDisabled.js, packages/react-native-webrtc/package.json, packages/react-native-webrtc/src/withBitcodeDisabled.ts
I found that while testing a webrtc build on a physical iOS device `expo run:ios -d` the build failed with: 
```
❌  ld: '/Users/evanbacon/Library/Developer/Xcode/DerivedData/withwebrtc-dmominfdhzvvbtawatnmnjajrizk/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/react-native-webrtc/WebRTC.framework/WebRTC' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/evanbacon/Library/Developer/Xcode/DerivedData/withwebrtc-dmominfdhzvvbtawatnmnjajrizk/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/react-native-webrtc/WebRTC.framework/WebRTC' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation) …
```
=> [webrtc] Fully disable bitcode to support development builds on physical devices

packages/detox/README.md, packages/detox/build/withDetox.d.ts, packages/detox/build/withNetworkSecurityConfig.d.ts, packages/detox/build/withNetworkSecurityConfig.js, packages/detox/src/__tests__/__snapshots__/withNetworkSecurityConfig-test.ts.snap, packages/detox/src/__tests__/withNetworkSecurityConfig-test.ts, packages/detox/src/withDetox.ts, packages/detox/src/withNetworkSecurityConfig.ts
The app crashes when `detox` plugin is configured with an empty subdomain in cases where it's desired to allow all traffic.
```
[
"@config-plugins/detox",
{
"subdomains": []
}
]
```
The configuration above generates an invalid xml resulting in a  `Caused by: [android.security.net](http://android.security.net/).config.XmlConfigSource$ParserException: No domain elements in domain-config at: Binary XML file line #3` as it generates
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
<domain-config cleartextTrafficPermitted="true">
</domain-config>
</network-security-config>
```
This PR inserts a `base-config` instead of a `domain-config` when subdomains is empty to allow all traffic.
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
<base-config …
```
=> chore(networkConfig): Fix android crash on empty subdomains config

packages/android-jsc-intl/package.json, packages/detox/CHANGELOG.md, packages/ffmpeg-kit-react-native/package.json, packages/ios-stickers/package.json, packages/react-native-adjust/package.json, packages/react-native-ble-plx/package.json, packages/react-native-blob-util/package.json, packages/react-native-branch/package.json, packages/react-native-callkeep/package.json, packages/react-native-dynamic-app-icon/package.json, packages/react-native-google-cast/package.json, packages/react-native-pdf/package.json, packages/react-native-quick-actions/package.json, packages/react-native-webrtc/CHANGELOG.md
The versions were committed incorrectly with https://github.com/expo/config-plugins/pull/52 this PR fixes the versions.
=> ci: fix versions

.releaserc.js
The npm package version wasn't being updated before, it appears that this is related to the order in which the plugins were arranged in the release config file. I've moved `npm` to be before `git` and `github`. My working theory is that this will bump the versions then commit rather than committing then bumping versions.
=> ci: change release config order

.github/workflows/pr-title.yml
I updated the title of [this PR](https://github.com/expo/config-plugins/pull/47) but it [failed](https://github.com/expo/config-plugins/runs/5562431256?check_suite_focus=true) with "Error: Resource not accessible by integration".
- Assuming that the [permissions required to make laber action work](https://github.com/actions/first-interaction/issues/10#issuecomment-1041402989) will apply here too, this change should fix the issue. 
- The changes didn't work so I've attempted to use the `statuses` permission directly since that appears to be what the [action is using](https://github.com/aslafy-z/conventional-pr-title-action/blob/61a635ab9df4031dd7876cafe3b4c85dc55f244e/src/index.js#L45).
- [Permissions docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-action …
=> ci: add statuses permissions to pr title workflow

packages/detox/build/withNetworkSecurityConfig.js, packages/detox/src/__tests__/__snapshots__/withNetworkSecurityConfig-test.ts.snap, packages/detox/src/withNetworkSecurityConfig.ts
This PR changes the xml templating so that it does not have leading spaces or new lines.
This is because leading whitespaces/new lines lead to the error:
"AAPT: error: XML or text declaration not at start of entity"
If neccessary I can create a reproduction repo tomorrow.
=> fix(detox): use improved xml generation

.github/workflows/test.yml, packages/react-native-branch/src/__tests__/fixtures/react-native-AndroidManifest.xml, packages/react-native-branch/src/__tests__/withBranchAndroid-test.ts, packages/react-native-branch/src/__tests__/withBranchIOS-test.ts, packages/react-native-branch/src/withBranchIOS.ts
- It's unclear if this works or not https://github.com/expo/config-plugins/pull/63
- Bring over tests from `@expo/prebuild-config`
- run tests locally
- tests should also show up in CI.
=> test: add tests for core plugin methods

README.md
Add a reference to another package that doesn't need a config plugin
Update the README to point to the package.
I created [a new Expo app](https://github.com/wodin/expo-multi-image-picker) based on the example app from [here](https://github.com/baronha/react-native-multiple-image-picker/tree/5c275b21c50848c7139cbdc87cca8cc7e9ee3317/example). I tested it on an Android device and on the iOS Simulator.
=> docs: add react-native-multiple-image-picker

README.md
Hi folks! I've made my first plugin for expo, which enables devs to use appcenter within the expo managed workflow!
https://www.npmjs.com/package/expo-appcenter
https://github.com/BelkaLab/expo-appcenter
I saw on [this issue](https://github.com/microsoft/appcenter/issues/189) it was something that community was asking for, so I gave it a try! 
I followed your guide on creating a plugin with typescript and all your conventions. If something is wrong, please give me feedback and I'll fix it :)
I've created a small app, installed the plugin and appcenter following [their guide](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native) and checked that the SDK was working.
=> docs: added expo-appcenter to plugins list

README.md
I've recently built an Expo config plugin for [react-native-keyevent](https://github.com/kevinejohn/react-native-keyevent). No public config plugin already exists for this library, so I felt it worth open sourcing and adding a link to the docs that most people are likely to look at.
=> feat(react-native-keyevent): Config plugin link in readme

packages/react-native-siri-shortcut/build/withReactNativeSiriShortcut.js, packages/react-native-siri-shortcut/src/__tests__/__snapshots__/withReactNativeSiriShortcut.test.ts.snap, packages/react-native-siri-shortcut/src/withReactNativeSiriShortcut.ts
@config-plugins/react-native-siri-shortcut breaks Universal Links on iOS - this fixes it.
Since [react-native-siri-shortcut always returns true](https://github.com/Gustash/react-native-siri-shortcut/blob/64c892e9d01cfa8d89c47a9287bf978b3213fd46/ios/RNSSSiriShortcuts.m#L85) the standard universal link functionality is never called.
By not returning based on the response from react-native-siri-shortcut.
By running - and updating - the unit tests. Also - by putting it into production today to fix the broken universal links :)
=> Fix broken Universal links

packages/detox/README.md
I ran into this and found it nearly impossible to figure out what caused it!
I'm not super sure about the config sample here. Is `process.env.EAS_BUILD_PROFILE` the right thing to check against here? Probably don't want to encourage opening up all domains for production apps...
=> docs(detox): Add "CLEARTEXT" error troubleshooting to README

apps/ios-stickers/app.json, apps/ios-stickers/package.json, package.json, packages/ios-stickers/README.md, packages/ios-stickers/build/options.json, packages/ios-stickers/build/withStickerAssets.d.ts, packages/ios-stickers/build/withStickerPack.js, packages/ios-stickers/build/withStickerXcodeTarget.d.ts, packages/ios-stickers/build/withStickerXcodeTarget.js, packages/ios-stickers/build/xcodeSticker.d.ts, packages/ios-stickers/build/xcodeSticker.js, packages/ios-stickers/src/__tests__/withStickerPack-test.ts, packages/ios-stickers/src/options.json, packages/ios-stickers/src/withStickerAssets.ts, packages/ios-stickers/src/withStickerPack.ts, packages/ios-stickers/src/withStickerXcodeTarget.ts, packages/ios-stickers/src/xcodeSticker.ts, yarn.lock
When migrating to expo while your react native project already have stickers, you may need to set a custom bundleId for the stickers project so your code signing will continue to work.
Add a new optional `stickerBundleId` Prop to the `withStickerPack` plugin
=> feat(ios-stickers): custom id for sticker project

packages/react-native-ble-plx/README.md, packages/react-native-ble-plx/build/withBLE.d.ts, packages/react-native-ble-plx/build/withBLE.js, packages/react-native-ble-plx/build/withBluetoothPermissions.d.ts, packages/react-native-ble-plx/build/withBluetoothPermissions.js, packages/react-native-ble-plx/src/withBLE.ts, packages/react-native-ble-plx/src/withBluetoothPermissions.ts
This permission is now fully deprecated as far as Expo is concerned (which has a lower baseline (iOS 13) than apps like Twitter (iOS 14)). We can now safely drop the permission https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothperipheralusagedescription
=> chore(react-native-ble-plx)!: drop `bluetoothPeripheralPermission` property

packages/ffmpeg-kit-react-native/build/withAndroidFFMPEGPackage.js, packages/ffmpeg-kit-react-native/src/withAndroidFFMPEGPackage.ts
Fixes #31.
The root cause of this is the issue described in the [ffmpeg-kit docs](https://github.com/tanersener/ffmpeg-kit/wiki/Tips#2-depending-another-android-library-containing-libc_sharedso):
> If a second library which also includes `libc++_shared.so` is added as a dependency, `gradle` fails with `More than one file was found with OS independent path 'lib/x86/libc++_shared.so'` error message.
This is currently breaking our build, so we're using `patch-package` to apply this diff.
Using https://github.com/expo/expo/pull/15863, which allows us to define a `android.packagingOptions.pickFirsts` property in `gradle.properties`.
Note that this currently doesn't check if there are any other `android.packagingOptions.pickFirsts` properties - I'm not even sure what the behavior should be in …
=> fix(ffmpeg-kit-react-native): fix Android build errors caused by duplicate libc++_shared.so

README.md
The link was incorrect—it just pointed implicitly to a non-existant path in this repository.
N/A
I tested the new link in the rendered markdown and confirmed it went to the npm package page just like the others do.
=> docs(readme): fix link to lyrahealth-inc/react-native-orientation-plugin

packages/react-native-pdf/README.md
Remove `fbjs` because it is not a dependency anymore in `react-native-pdf`
https://github.com/wonday/react-native-pdf/releases/tag/v6.5.0
Incorrect docs
=> remove `fbjs` dependency

README.md
The React Native Firebase is missing `"@react-native-firebase/crashlytics"` from the list and can be confusing as to why there is a parity between this doc and the actual React Native Firebase docs: https://rnfirebase.io/#expo-managed-workflow
=> [docs] Update React Native Firebase plugin list

apps/react-native-dynamic-app-icon/app.json, packages/react-native-dynamic-app-icon/src/index.ts
This is an attempt to satisfy Apple's request for dynamic app icons on iPad, using sizes `152x152` and `167x167`.
- See: https://developer.apple.com/design/human-interface-guidelines/app-icons#iOS-iPadOS-app-icon-sizes
- See: https://stackoverflow.com/a/70986182
- Replaced fixed `size` and `scales` with `IconDimension`
- Added iPad specific icon dimensions, turning on/off based on `ios.supportsTablets`
- Run example app `apps/react-native-dynamic-app-icon`
- iPad support is now enabled
- Verify that iPad icons are exported + registered, and plist contains right icon info
=> fix(react-native-dynamic-app-icon): add exact ipad sizes `152`/`167` for exported icons

README.md
Freshchat's RN implementation requires some native changes. I wanted to build a plugin to help users quickly apply these changes consistently when using CNG.
This plugin follows the steps outlined in [Freshchat SDK documentation](https://developers.freshchat.com/mobile/#getting-started)
No tests required, this is a doc change only
=> feat: adds expo-react-native-freshchat to out-of-tree plugin list

.github/workflows/test.yml
v2 will stop working in February.
=> chore: update actions/cache v2 -> v4

packages/react-native-branch/android/build.gradle, packages/react-native-branch/package.json
Branch integration is broken with SDK 52: https://github.com/expo/config-plugins/issues/259
The namespace is incorrect.
=> fix(branch): Fix branch plugin namespace
